version: '3.8'
services:

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: cocksteady/foodgram_back:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env
    command: >
       sh -c 'python manage.py migrate &&
              python manage.py collectstatic --no-input &&
              python manage.py csv_ingredients_import &&
              gunicorn --bind 0:8000 foodgram.wsgi'
    depends_on:
      - db

  frontend:
    image: cocksteady/foodgram_front:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web
 
  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  postgres_value:
