# Generated by Django 4.1.4 on 2023-01-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
