# Generated by Django 4.1.4 on 2023-01-09 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_delete_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, "Количество ингридиентов должно быть больше нуля."
                    )
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="favoritelist",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_favorite"
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppinglist",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_shopping"
            ),
        ),
    ]
