# Generated by Django 4.1.4 on 2023-01-13 12:10

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipeingredient_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[recipes.validators.validate_lowercase],
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=200,
                unique=True,
                validators=[recipes.validators.validate_lowercase],
            ),
        ),
    ]
