# Generated by Django 4.1.4 on 2023-01-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_ingredient_measurement_unit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "verbose_name": "ингридиент",
                "verbose_name_plural": "ингридиенты",
            },
        ),
    ]
