# Generated by Django 4.1.4 on 2023-01-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_ingredient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ("name",),
                "verbose_name": "ингридиент",
                "verbose_name_plural": "ингридиенты",
            },
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="tag",
            new_name="tags",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredient",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.RecipeIngredient", to="recipes.ingredient"
            ),
        ),
    ]
