# Generated by Django 4.1.4 on 2023-01-16 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_ingredient_options_rename_tag_recipe_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "default_related_name": "recipe_ingredient",
                "ordering": ("recipe",),
                "verbose_name": "ингридиент к рецепту",
                "verbose_name_plural": "ингридиенты к рецепту",
            },
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, "Количество ингридиентов должно быть больше нуля."
                    )
                ]
            ),
        ),
    ]
