# Generated by Django 4.1.4 on 2023-01-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_alter_ingredient_name_alter_recipeingredient_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
