# Generated by Django 4.1.4 on 2023-01-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_alter_ingredient_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(max_length=300, upload_to="recipes/"),
        ),
    ]
