# Generated by Django 4.1.4 on 2023-01-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(max_length=300, upload_to="recipes/images/"),
        ),
    ]
